/**:
  ros__parameters:
    joints_map:
      left_front:
        - motor_front_left_shoulder
        - motor_front_left_leg
        - foot_motor_front_left
      right_front:
        - motor_front_right_shoulder
        - motor_front_right_leg
        - foot_motor_front_right
      left_hind:
        - motor_rear_left_shoulder
        - motor_rear_left_leg
        - foot_motor_rear_left
      right_hind:
        - motor_rear_right_shoulder
        - motor_rear_right_leg
        - foot_motor_rear_right
